FROM alpine:3.10

WORKDIR /workspace

RUN \
    apk add --no-cache \
        openssl-dev=1.1.1d-r2 \
        nano=4.3-r0 \
        openssh=8.1_p1-r0 \
        bash=5.0.0-r0 \
        git=2.22.2-r0 \
        nodejs=10.16.3-r0 \
        npm=10.16.3-r0 \
        yarn=1.16.0-r0